CupThrow/config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'
  get 'home/game'
  get 'home/items'
  post 'home/throw_cup'
  post 'home/buy_dice'
  post 'home/buy_coins'
  get 'home/init_player', to: 'home#init_player', :as => 'init_player'
  get 'home/throw_cup', to: 'home#throw_cup', :as => 'throw_cup'
  get 'home/buy_dice', to: 'home#buy_dice', :as => 'buy_dice'
  get 'home/buy_coins', to: 'home#buy_coins', :as => 'buy_coins'
  get 'home/new_game', to: 'home#new_game', :as => 'new_game'
  
  devise_for :users
  resources :users
  
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

CupThrow/app/controllers/home_controller.rb
require_relative './A1/A1_Classes.rb'

class HomeController < ApplicationController
 
  def index
    @users = User.all
  end

  def init_player 
    @player = Player.new(current_user.name)
    h1 = Hand.new
  
    c1 = Coin.new(0.25)
    c2 = Coin.new(0.25)
    c3 = Coin.new(0.25)

    d1 = Die.new(6, :white)
    d2 = Die.new(6, :white)
    d3 = Die.new(6, :white)
    
    # store all init randomizers in player's bag
    h1.store_all [c1, c2, c3, d1, d2, d3]
    p1.move_all(h1)

    redirect_to home_game_path 
  end 

  def throw_cup
    current_user.bag = "currgame"
    current_user.name
    current_user.user_score = 16
    current_user.save
    render 'game' 
  end 

  def buy_coins
    # current_user.coins = 1s
    cost = params[:coins_count].to_i * 2
    current_user.gems = current_user.gems - cost
    current_user.save
    render 'items' 
  end

  def buy_dice
    cost = params[:dice_count].to_i * params[:dice_sides].to_i
    current_user.gems = current_user.gems - cost
    current_user.save
    render 'items' 
  end

end

CupThrow/app/helpers/home_helper.rb
module HomeHelper
end

CupThrow/app/views/home/game.html.erb
<div class="container-fluid" style="margin-left:100px;">

    <h1><%= 'Make a Throw' %></h1>

    <br/>

    <p class="nav-item" style="margin-top:8px; padding-right:20px">
        <%= image_tag("avatar.png", size: "30x30", alt: "Point", style: 'display:inline') %>
        <%= 'Player 1: ' + current_user.name %>
    </p>

    <p class="nav-item" style="margin-top:8px; padding-right:20px">
        <%= image_tag("computer.jpeg", size: "30x30", alt: "Point", style: 'display:inline') %>
        <%= 'Player 2: Computer' %></p>
    </p>
    
        <% if current_user.bag == "currgame" %>
            <%= 'Your throw result =' %>
            <%= current_user.user_score = rand(10...30) %>
            <% current_user.save %>
            <br/><br/>

            <%= 'The computer\'s throw result =' %>
            <% computer_score = rand(10...30) %>
            <%= computer_score %>
            <br/><br/>

            <% if computer_score > current_user.user_score %>
                <h2 style="color: red;"><%= 'Computer wins, hard luck!' %></h2>
            <% elsif computer_score == current_user.user_score %>
                <h2><%= 'It\'s a tie!' %></h2>
            <% else %>
                <h2 style="color: blue;"><%= 'You win, congrats!' %></h2>
                <p><%= 'Checkout your updated gems above.' %></p>

                <% current_user.points += current_user.user_score %>
                <% current_user.gems += current_user.user_score - computer_score %>
                <% current_user.save %>
            <% end %>

            <% current_user.bag = "newgame" %>
            <% current_user.save %>

            <br/>
            <%= button_to "Throw Again", type: "button", action: "throw_cup", class: "btn btn-dark" %>
            <br/>

        <% else %>
            <p><%= 'Rules of the Game: ' %></p>
            <p><%= '1. Make adjustments to your bag by filling out the form to add dice and coins.' %></p>
            <p><%= '2. After filling the form i.e. your bag, click Throw.' %></p>
            <p><%= '3. Next is the Computer\'s turn, it will make its own Throw.' %></p>
            <p><%= '4. The player with the highest throw result wins the game. ' %></p>
        <% end %>

    <%= form_tag('throw_cup', method: 'post') do %>

        <br/>

        <label>Coin Denomination</label>
        <%= text_field_tag '@coin_denomination', nil, placeholder: '0.25' %>
        <br/><br/>

        <label>Number of Coins</label>
        <%= text_field_tag '@coin_count', nil, placeholder: '1' %>
        <br/><br/>

        <label>Dice Colour</label>
        <%= text_field_tag '@dice_colour', nil, placeholder: ':white' %>
        <br/><br/>

        <label>Dice Sides</label>
        <%= text_field_tag '@dice_sides', nil, placeholder: '6' %>
        <br/><br/>

        <label>Number of Dice</label>
        <%= text_field_tag '@dice_count', nil, placeholder: '1' %>
        <br/><br/>
       
        <%= button_to "Throw", type: "button", action: "throw_cup", class: "btn btn-dark" %>
        
        <br/><br/>

    <%= link_to "End Game   ", home_index_path, type: "button", action: "", class: "btn btn-secondary" %>
        <br/><br/><br/>

    <% end %>
    
</div>

CupThrow/app/views/home/index.html.erb
<% welcome_msg = current_user.present? ? 'Hi, ' + current_user.name : 'Welcome to CupThrow Game' %>

    <% if user_signed_in? %>

    <div class="container-fluid" style="margin-left:100px;">
    <h1><%= welcome_msg %></h1>

        <%= form_tag('init_player', method: 'post') do %>
    
        <br/>

        <p>
            <%= 'Your ' %>
            <%= image_tag("bag.png", size: "40x40", alt: "Bag", style: 'display:inline') %>
            <%= ' contains ' %>
            <%= @about_me %>

        </p>

        <table class="table table-striped" style="max-width: 700px;">
            <thead>
            <tr>
                <th>Item</th>
                <th>Count</th>
                <th>Description</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td><%= 'Coin' %></td>
                    <td><%= current_user.default_coin_count %></td>
                    <td><%= current_user.default_coin_den %></td>
                </tr>
                <tr>
                    <td><%= 'Die' %></td>
                    <td><%= current_user.default_dice_count %></td>
                    <td><%= current_user.default_dice_colour + ', ' + current_user.default_dice_sides + ' sided' %></td>
                </tr>
            </tbody>
        </table>

        <br/>
        <br/>

        <%= link_to "Play a Game", home_game_path, type: "button", action: "", class: "btn btn-dark" %>

        <%= link_to "Purchase Items", home_items_path, type: "button", action: "", class: "btn btn-dark" %>

        </div>
        <% end %>

    <% else %>
        <%= image_tag("n.png", style: 'width:100%;height:auto;', alt: "Edit Entry") %>
    <% end %>
    

CupThrow/app/views/home/items.html.erb
<div class="container-fluid" style="margin-left:100px;">

    <h1><%= 'Purchase Items' %></h1>

    <%= form_tag "buy_coins", method: "post" do %>

        <p><%= '1. Make adjustments to your bag by filling out the form to purchase dice and coins.' %></p>
        <p><%= '2. Click buy to perform your transaction, the cost is 1 gem per side. ' %></p>
        <p><%= '3. Checkout your gems above, they\'ll be updated accordingly. ' %></p>

        <br/>

        <p class="nav-item" style="margin-top:8px; padding-right:20px">
            <%= 'Buy ' %>
            <%= image_tag("coins.png", size: "60x60", alt: "Coins", style: 'display:inline') %>
        </p>

        <label>Coin Denomination</label>
        <%= text_field_tag "coins_denomination", nil, placeholder: '0.25' %>
        <br/><br/>

        <label>Number of Coins</label>
        <%= text_field_tag "coins_count", nil, placeholder: '0.25' %>
        <br/><br/>

        <%= button_to "Buy Coins", type: "button", action: "buy_coins", class: "btn btn-dark" %>
        <br/><br/>

    <% end %>

    <%= form_tag "buy_dice", method: "post" do %>

        <p class="nav-item" style="margin-top:8px; padding-right:20px">
            <%= 'Buy ' %>
            <%= image_tag("dice.png", size: "70x50", alt: "Dice", style: 'display:inline') %>
        </p>
    
        <label>Dice Colour</label>
        <%= text_field_tag "dice_colour", nil, placeholder: ':white' %>
        <br/><br/>

        <label>Dice Sides</label>
        <%= text_field_tag "dice_sides", nil, placeholder: '6' %>
        <br/><br/>

        <label>Number of Dice</label>
        <%= text_field_tag "dice_count", nil, placeholder: '1' %>
        <br/><br/>

        <%= button_to "Buy Dice", type: "button", action: "buy_dice", class: "btn btn-dark" %>

        <br/>

    <%= link_to "Back to Profile", home_index_path, type: "button", action: "", class: "btn btn-secondary" %>
    <br/><br/><br/>

    <% end %>

</div>